platform :ios, '8.0'
use_frameworks!
target 'MT_BSBDJ_Swift' do
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'Alamofire', '~> 3.1.5'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'Kingfisher', '~> 2.0.1'
    pod 'DACircularProgress', '~> 2.3.1'	
    pod ‘SVProgressHUD’

end

